# Generated by Django 4.2.11 on 2025-09-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_sql_to_postrge_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="title",
            field=models.TextField(verbose_name="title"),
        ),
    ]
